<a href="https://colab.research.google.com/github/sajid-the-data-guy/Libraries_DS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


In [67]:
import numpy as np


In [68]:
#1dimenstion numpy array
my_array = np.array([3,6,32,7])

In [69]:
print(type(my_array), my_array)

<class 'numpy.ndarray'> [ 3  6 32  7]


In [70]:
my_array[1],my_array[-1]

(6, 7)

In [71]:
#2 dimenstion numpy array
arr = np.array([[13,23,12, 12],[21,42,23,42]])
print(arr)

[[13 23 12 12]
 [21 42 23 42]]


In [72]:
#to get 23 and 42 
arr[0,1],arr[1,-1]

(23, 42)

In [73]:
#changing the array in position of 0,1 
arr[0,1]=45
print(arr)

[[13 45 12 12]
 [21 42 23 42]]


## Array creation: Convertion from other python structures


In [74]:
list_array = np.array([[1,2,4], [5,8,5],[0,3,1]])
print(list_array)

[[1 2 4]
 [5 8 5]
 [0 3 1]]


In [75]:
list_array.shape

(3, 3)

In [76]:
list_array.dtype

dtype('int64')

In [77]:
n_set = np.array({23,42,51})
a = {23,523,51}
type(a)

set

In [78]:
type(n_set)

numpy.ndarray

In [79]:
#creating a array full of zero values
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
#range in numpy
rng = np.arange(15)
rng
#it will print 0 to 14 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
#equally elements 
lspace = np.linspace(0,50,25)
lspace

array([ 0.        ,  2.08333333,  4.16666667,  6.25      ,  8.33333333,
       10.41666667, 12.5       , 14.58333333, 16.66666667, 18.75      ,
       20.83333333, 22.91666667, 25.        , 27.08333333, 29.16666667,
       31.25      , 33.33333333, 35.41666667, 37.5       , 39.58333333,
       41.66666667, 43.75      , 45.83333333, 47.91666667, 50.        ])

In [104]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [105]:
arr.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [108]:
arr.shape

(100,)

In [113]:
#changing into one dimension array
arr = arr.ravel()
arr.shape

(100,)

In [115]:
#doing sum in the column
#creating a list first
list_arr = [[1,2,3],[2,3,4],[5,6,7]]
list_arr = np.array(list_arr)

In [116]:
list_arr

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [117]:
ar = list_arr
ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [118]:
#sum of column we have got
ar.sum(axis=0)

array([ 8, 11, 14])

In [119]:
#sum of row in array
ar.sum(axis=1)

array([ 6,  9, 18])

In [120]:
#iterate the all item in the array
ar.flat

In [121]:
for item in ar.flat:
  print(item)

1
2
3
2
3
4
5
6
7


In [123]:
ar.ndim

2

In [124]:
#arbits to investigate the array bits
ar.nbytes

72

In [126]:
#to view the maximum element in the array by using arg function
one = np.array([1,24,2512,55353, 32])
one.argmax()

3

In [127]:
#to find the index of the arg min
one.argmin()

0

In [128]:
#to find the  index of the array in ascending order
one.argsort()

array([0, 1, 4, 2, 3])

In [129]:
 ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [131]:
ar.argmax()

8

In [133]:
ar.ravel()

array([1, 2, 3, 2, 3, 4, 5, 6, 7])

In [135]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [136]:
ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [137]:
ar2= np.array([[2,2,2],[3,3,3],[4,4,4]])

In [140]:
ar3= ar2 + ar
ar3

array([[ 3,  4,  5],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [141]:
ar1 = np.array([5,5,5])

In [142]:
ar1+ar

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [10, 11, 12]])

In [143]:
#what happen if we add list values
[1,2,4] + [3,4,1]

[1, 2, 4, 3, 4, 1]

In [147]:
ar3

array([[ 3,  4,  5],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [149]:
#find the greater value than 7 in ar3
np.where(ar3>9)

(array([2, 2]), array([1, 2]))